In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b2 = np.array([[12,34,54,56],[1.2,34.45,4.65,7.89]])
print(b2)

[1 2 3]
[[1 2 3 4]
 [5 6 7 8]]
[[12.   34.   54.   56.  ]
 [ 1.2  34.45  4.65  7.89]]


In [2]:
# Get Dimension
print(f"Dimension of a is: {a.ndim}")

Dimension of a is: 1


In [3]:
# Get Dimension
print(f"Dimension of a is: {b.ndim}")

Dimension of a is: 2


In [4]:
# Get Shape of the array...
print(f"Shape of a is: {a.shape}")
print(f"Shape of a is: {b.shape}")

Shape of a is: (3,)
Shape of a is: (2, 4)


In [5]:
# Get Type: 
a.dtype

dtype('int64')

In [6]:
a = np.array([1,2,3],dtype = 'int8')


In [7]:
# Get Type: 
a.dtype

dtype('int8')

In [8]:
# Get Size: 
a.itemsize

1

In [9]:
a = np.array([1,2,3],dtype = 'int32')

In [10]:
a.itemsize

4

In [11]:
'''
itemsize: Gives the size of individual element in the array
size    : Gives the size of the array itself 
Therefore total size will be arr.itemsize*arr.size
nbytes: Gives the product of the above 2
'''
size = a.itemsize * a.size
print(f"Size/Item_count of array a: {a.size}\nSize of items: {a.itemsize}\nTotal size of the array is: {size}")
print(f"Size is: {a.nbytes}")

Size/Item_count of array a: 3
Size of items: 4
Total size of the array is: 12
Size is: 12
