# Numpy Basic Operations

## Creating multi dimensional Arrays

In [2]:
import numpy as np

In [ ]:
arr1 = np.array([[i for i in range(1,11,2)],[i for i in range(2,11,2)]])
print(arr1)

In [3]:
c = np.array([[i for i in range(1,11,2)],[i for i in range(2,11,2)]],dtype = complex)
print(c)

[[ 1.+0.j  3.+0.j  5.+0.j  7.+0.j  9.+0.j]
 [ 2.+0.j  4.+0.j  6.+0.j  8.+0.j 10.+0.j]]


In [ ]:
arr2 = np.reshape(arr1,(5,2))
print(arr2)

In [ ]:
arr2 = np.transpose(arr1)
print(arr2)

In [ ]:
print(arr1.dtype,arr2.dtype,c.dtype)

In [ ]:
zero_arr = np.zeros((3,3))
ones_arr = np.ones((3,3),dtype = np.int16)
random = np.empty((3,3))
print(zero_arr,ones_arr,random,sep = "\n")

In [ ]:
# Array with same elements
e = np.full((2,2),7)
print(e)

In [ ]:
# Array identity matrix
print(np.eye(3))

In [ ]:
# arange()
b_arr = np.arange(1,11,1)
print(b_arr)

In [ ]:
# linspace()
print(np.linspace(0.2,9,10)) # (start, end, no. of elements)

In [ ]:
from numpy import pi
print(np.sin(np.linspace(0,2*pi,100)))

##                            Basic Operations

In [ ]:
# Product of two matrix 
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Element wise multiplication\nA*B\n{A*B}")
print(f"Matrix multiplication\nA@B\n{A@B}")
print(f"Matrix multiplication using dot() function:\n{A.dot(B)}")

## Aggregate Functions

In [9]:
b = np.arange(1,10,1).reshape((3,3))
print(b)
print(b.sum())
print(np.sum(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
45


In [7]:
print(b.max(axis = 0))
print(b.max(axis = 1))

[7 8 9]
[3 6 9]


## Copying Array

In [ ]:
a = np.arange(1,10,2)
h=a.view()
print(h)
a = a*2
print(h)

In [ ]:
a = np.arange(1,10,2)
h=a.copy()
print(h)
a = a*2
print(h)

## Changing Array Shape


In [ ]:
s = np.array([[1,2,3],[4,5,6]],dtype = float)
print(s)